#version: "3.8"
#
#services:
#
#  postgres:
#    image: postgres:17
#    container_name: postgres-db
#    restart: always
#    environment:
#      POSTGRES_DB: docker
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: zenin@yutaaa9999
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#
#  springboot-app:
#    build: .
#    container_name: springboot-app
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/docker
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: zenin@yutaaa9999
#      SPRING_JPA_SHOW_SQL: "true"
#      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
#
#volumes:
#  postgres_data:

version: "3.8"

services:
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d6nujip5pdvs73fu7kf0-a:5432/docker_demo_db_yj2n
      SPRING_DATASOURCE_USERNAME: docker_demo_db_yj2n_user
      SPRING_DATASOURCE_PASSWORD: 7MO10Gufd8YMzpvYb411MA9TMmR6Sy35
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"