spring.application.name=spring-data-redis-cache
server.port=8080

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/redis_cache
spring.datasource.username=postgres
spring.datasource.password=zenin@yutaaa9999
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ORM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Redis Cache
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379