#events{} it's just a required block of nginx for request connection
events {}


http {
    # upstream servers is a server for create a group backend server
    # who nginx will load balancing of spring boot app container
    upstream spring_servers {
        server spring-boot-api1:8080;
        server spring-boot-api2:8080; #container spring name
        server spring-boot-api3:8080;
    }

    #server is block of server configuration
    server {
    server_tokens off;
        listen 80; #nginx server will catch request on HTTP port 80

        #location is show block all request HTTP
        location / {
            proxy_pass http://spring_servers; #nginx sent request to upstream spring_servers
            proxy_set_header Host $host; #sent header infomation to backend and nginx syntax
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}